language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
before_install:
 # - sudo add-apt-repository ppa:mc3man/trusty-media -y
 # - sudo apt-get -qq update
 # - sudo apt-get install ffmpeg gstreamer0.10-ffmpeg libav-tools libgdiplus libavcodec-extra  libtheora-dev -y
 # - sudo apt-cache policy libav-tools
script:
 - dotnet restore
 - dotnet test Xabe.FFmpeg.Test/
 - dotnet clean -c Release
 - cd Xabe.FFmpeg
 - if [[ -z "${TRAVIS_TAG}" ]]; then 
 -  dotnet build /p:GenerateDocumentationFile=true
 - 	dotnet pack --no-build -o nuget /p:GenerateDocumentationFile=true
 - else
 - 	dotnet build -c Release /property:Version=$TRAVIS_TAG /p:GenerateDocumentationFile=true
 - 	dotnet pack --no-build -c Release -o nuget /p:PackageVersion=$TRAVIS_TAG /p:GenerateDocumentationFile=true
 - 	dotnet nuget push nuget/*.nupkg -k $NUGET_API -s https://www.nuget.org/api/v2/package
 - fi
